---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Create Docker service config dir
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: Create Docker proxy config
  template: src=proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf owner=root mode=0644
  when: '"http_proxy" in calc_proxy_env or "https_proxy" in calc_proxy_env'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
